# Generated by Django 2.1.11 on 2019-08-12 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0002_auto_20190807_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fav_user_id', models.ImageField(upload_to='')),
                ('favtweet', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fav_number', to='tweet.Tweet')),
            ],
        ),
    ]
